import os
import time
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from schemas.costing import CostEstimationResponse

def generate_cost_boq_pdf(cost_data: CostEstimationResponse, filename: str) -> str:
    """
    Generates a professional BOQ PDF for cost estimation results.
    Returns the absolute path of the generated file.
    """
    doc = SimpleDocTemplate(filename, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = styles['Title']
    heading_style = styles['Heading2']
    normal_style = styles['Normal']
    
    # Header
    elements.append(Paragraph("BILL OF QUANTITIES (Materials Only)", title_style))
    elements.append(Spacer(1, 12))
    
    # Metadata
    date_str = time.strftime("%Y-%m-%d %H:%M:%S")
    elements.append(Paragraph(f"<b>Project:</b> Automated Construction Estimate", normal_style))
    elements.append(Paragraph(f"<b>Generated:</b> {date_str}", normal_style))
    elements.append(Paragraph(f"<b>Context:</b> {cost_data.context}", normal_style))
    elements.append(Paragraph(f"<b>Currency:</b> {cost_data.currency}", normal_style))
    elements.append(Spacer(1, 24))
    
    # Table Data
    # Headers
    data = [["Item Description", "Quantity", "Unit", "Rate", "Amount"]]
    
    # Rows
    for item in cost_data.line_items:
        row = [
            item.item,
            f"{item.quantity:,.2f}",
            item.unit,
            f"{item.rate:,.0f}",
            f"{item.amount:,.0f}"
        ]
        data.append(row)
        
    # footer row (Total)
    data.append([
        "TOTAL PROJECT COST", 
        "", 
        "", 
        "", 
        f"{cost_data.total_project_cost:,.0f}"
    ])
    
    # Table Styling
    # Column widths: Description (wide), Qty, Unit, Rate, Amount
    col_widths = [220, 60, 50, 80, 100]
    t = Table(data, colWidths=col_widths)
    
    # Styling
    t.setStyle(TableStyle([
        # Header Row
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkgrey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        
        # Body
        ('GRID', (0, 0), (-1, -2), 0.5, colors.grey),
        ('ALIGN', (1, 1), (-1, -1), 'RIGHT'), # Numbers right aligned
        ('ALIGN', (0, 1), (0, -1), 'LEFT'),   # Description left aligned
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        
        # Total Row (Last row)
        ('BACKGROUND', (0, -1), (-1, -1), colors.lightgrey),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0, -1), (-1, -1), colors.black),
        ('ALIGN', (0, -1), (-1, -1), 'RIGHT'), # Align "Total" label and amount
        ('SPAN', (0, -1), (3, -1)),            # Span first 4 columns for "Total" label
    ]))
    
    elements.append(t)
    elements.append(Spacer(1, 30))
    
    # Footer
    footer_style = ParagraphStyle('Footer', parent=normal_style, alignment=1, fontSize=8, textColor=colors.grey)
    elements.append(Paragraph("Generated by AI Construction Estimator", footer_style))
    elements.append(Paragraph("Disclaimer: Estimates are based on theoretical quantities and standard rates. Actual site costs may vary.", footer_style))
    
    # Build
    doc.build(elements)
    return filename
